packages:
  - "packages/*"
  - "packages/e2e/fixtures/*"

overrides:
  react: ^19.2.4
  react-dom: ^19.2.4

minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - "@voidzero-dev/*"
  - vite-plus
  - "@vitest/*"
  - vite
  - vitest
  - "@oxc-project/*"
  - "@oxlint/*"
  - oxlint
  - oxfmt
  - oxlint-tsgolint
blockExoticSubdeps: false
